routes/web.php
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => 'guest'], function () {
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('login.act');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.token');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});

Route::group(['middleware' => 'auth'], function () {
    Route::middleware('role:owner_or_manager_kantorpusat|manager_or_admin_toko|sales')->group(function () {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::post('dashboard', 'DashboardController@getData')->name('dashboard.getdata');
    
        Route::get('dashboard/view-top-produk', 'DashboardController@viewTopPrd')->name('view-top-produk');
        Route::post('dashboard/view-top-produk', 'DashboardController@getDataTopPrd')->name('view-top-produk.getdata');
    
        Route::get('dashboard/view-all-customer', 'DashboardController@viewAllCst')->name('view-all-customer');
        Route::post('dashboard/view-all-customer', 'DashboardController@getAllCst')->name('view-all-customer.getdata');
        Route::post('dashboard/view-all-customer/broadcast', 'DashboardController@broadcastCst')->name('view-all-customer.broadcast');
    
        Route::get('dashboard/view-all-category', 'DashboardController@viewAllCat')->name('view-all-category');
        Route::post('dashboard/view-all-category', 'DashboardController@getAllCat')->name('view-all-category.getdata');
    
        Route::get('dashboard/view-all-sales-user', 'DashboardController@viewAllSales')->name('view-all-sales.user');
        Route::post('dashboard/view-all-sales-user', 'DashboardController@getAllSales')->name('view-all-sales.getdata'); 
        
        Route::get('dashboard/view-all-store-contribution', 'DashboardController@viewAllStoreContribution')->name('view-all-store-contribution.store');
        Route::post('dashboard/view-all-store-contribution', 'DashboardController@getAllStoreContribution')->name('view-all-store-contribution.getdata'); 
    });
    
    Route::get('my-profile', 'AccountSettingController@myprofile')->name('myprofile.index');
    Route::post('edit-profile', 'AccountSettingController@updateprofile')->name('myprofile.update');

    Route::get('change-password', 'AccountSettingController@changepassword')->name('change-password.index');
    Route::post('change-password', 'AccountSettingController@updatepassword')->name('change-password.update');

    Route::prefix('master-data')->group(function () {
        Route::middleware('role:owner_or_manager_kantorpusat|manager_or_admin_toko')->group(function () {
            Route::resource('supplier', 'MasterData\SupplierController')->except(['show', 'create']);
            Route::resource('produsen', 'MasterData\ProdusenController')->except(['show', 'create']);
            Route::resource('satuan', 'MasterData\SatuanController')->except(['show', 'create']);
            Route::resource('kategori-material', 'MasterData\KategoriMaterialController')->except(['show', 'create']);
            Route::resource('kategori-produk', 'MasterData\KategoriProdukController')->except(['index', 'show', 'create']);
            Route::resource('daerah', 'MasterData\DaerahController')->except(['show', 'create']);
            Route::resource('collection', 'MasterData\CollectionController')->except(['show', 'create']);
            Route::get('currency', 'MasterData\CurrencyController@index')->name('currency.index');
        });
        Route::resource('location', 'MasterData\LocationController')->middleware('role:owner_or_manager_kantorpusat')->except(['show', 'create']);
        Route::resource('data-user', 'MasterData\DataUserController')->middleware('role:owner_or_manager_kantorpusat')->except(['show', 'create']);
    });

    Route::prefix('inventory')->group(function () {
        Route::middleware('role:owner_or_manager_kantorpusat|manager_or_admin_toko')->group(function () {
            Route::post('produk/stock/getlocation', 'Inventory\StokProdukController@getlocation')->name('stok-produk.getlocation');
            Route::get('produk/stock/{prd_id}', 'Inventory\StokProdukController@index')->name('stok-produk.index');
            Route::post('produk/stock/{prd_id}', 'Inventory\StokProdukController@store')->name('stok-produk.store');
            Route::delete('produk/stock/{id}', 'Inventory\StokProdukController@destroy')->name('stok-produk.destroy');

            Route::get('produk/barcode/{prd_id}/print', 'Inventory\ProdukController@barcodePrint')->name('produk.print-barcode');
            Route::get('produk/cekkdproduk/{kdproduk}', 'Inventory\ProdukController@cekkdproduk')->name('produk.cekkdproduk');
            Route::get('produk/getdata', 'Inventory\ProdukController@getData')->name('produk.getData');
            Route::post('produk/getkode', 'Inventory\ProdukController@getKode')->name('produk.getKode');
            Route::resource('produk', 'Inventory\ProdukController')->except(['show', 'create']);

            Route::get('produk/discount', 'Inventory\DiscountProdukController@index')->name('diskon-produk.index');
            Route::post('produk/set-discount', 'Inventory\DiscountProdukController@setDiskon')->name('diskon-produk.set-diskon');

            Route::post('produk/komposisi/getmaterial', 'Inventory\KomposisiProdukController@getmaterial')->name('komposisi-produk.getmaterial');
            Route::get('produk/komposisi/{prd_id}', 'Inventory\KomposisiProdukController@index')->name('komposisi-produk.index');
            Route::post('produk/komposisi/{prd_id}', 'Inventory\KomposisiProdukController@store')->name('komposisi-produk.store');
            Route::get('produk/komposisi/{id}/edit', 'Inventory\KomposisiProdukController@edit')->name('komposisi-produk.edit');
            Route::patch('produk/komposisi/{id}', 'Inventory\KomposisiProdukController@update')->name('komposisi-produk.update');
            Route::delete('produk/komposisi/{id}', 'Inventory\KomposisiProdukController@destroy')->name('komposisi-produk.destroy');

            Route::get('stock-opname', 'Inventory\StockOpnameController@index')->name('stock-opname.index');
            Route::get('stock-opname/download-stock/{kdloc}', 'Inventory\StockOpnameController@downloadStock')->name('stock-opname.downloadstock');
            Route::get('stock-opname/create', 'Inventory\StockOpnameController@create')->name('stock-opname.create');
            Route::post('stock-opname/create', 'Inventory\StockOpnameController@readImport')->name('stock-opname.readimport');
            Route::post('stock-opname/store', 'Inventory\StockOpnameController@store')->name('stock-opname.store');
            Route::get('stock-opname/{id}/detail', 'Inventory\StockOpnameController@detail')->name('stock-opname.detail');
            Route::get('stock-opname/{id}/export', 'Inventory\StockOpnameController@export')->name('stock-opname.export');
            Route::patch('stock-opname/{id}', 'Inventory\StockOpnameController@update')->name('stock-opname.update');
            Route::delete('stock-opname/{id}', 'Inventory\StockOpnameController@cancel')->name('stock-opname.cancel');

            Route::get('stock-card', 'Inventory\StockCardController@index')->name('stock-card.index');
            Route::post('stock-card', 'Inventory\StockCardController@getdata')->name('stock-card.getdata');
            Route::post('stock-card/get-list-item', 'Inventory\StockCardController@getListItem')->name('stock-card.getListItem');
            Route::get('stock-card/{start}/{end}', 'Inventory\StockCardController@cetakStock')->name('stock-card.cetak');

            //Route::get('summary-stock', 'Inventory\SummaryStockController@index')->name('summary-stock.index');
            //Route::post('summary-stock', 'Inventory\SummaryStockController@getdata')->name('summary-stock.getdata');
            //Route::get('summary-stock/{start}/{end}', 'Inventory\SummaryStockController@cetakStock')->name('summary-stock.cetak');

            Route::get('summary-stock-outlet', 'Inventory\SummaryStockOutletController@index')->name('summary-stock-outlet.index');
            Route::post('summary-stock-outlet', 'Inventory\SummaryStockOutletController@getdata')->name('summary-stock-outlet.getdata');
            Route::get('summary-stock-outlet/{start}/{end}', 'Inventory\SummaryStockOutletController@exportStock');

            Route::get('summary-stock-outlet2', 'Inventory\SummaryStockOutletController@index2')->name('summary-stock-outlet.index2');
            Route::post('summary-stock-outlet2', 'Inventory\SummaryStockOutletController@getdata2')->name('summary-stock-outlet.getdata2');

            Route::get('summary-stock-global', 'Inventory\SummaryStockGlobalController@index')->name('summary-stock-global.index');
            Route::post('summary-stock-global', 'Inventory\SummaryStockGlobalController@getdata')->name('summary-stock-global.getdata');

            Route::get('stock-allert', 'Inventory\StockAllertController@index')->name('stock-allert.index');
            Route::post('stock-allert/create-costing', 'Inventory\StockAllertController@createCosting')->name('stock-allert.create-costing');

            Route::resource('product-reject', 'Inventory\ProdukRejectController')->only(['index', 'store']);
        });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\MailSendResetLink;
use Illuminate\Notifications\Notifiable;
use Illuminate\Http\UploadedFile;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'tb_user';
    protected $guarded = [];
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getUserProfileAttribute()
    {
        if ($this->img_profile != '') {
            return asset('storage/user/' . $this->img_profile);
        } else {
            return asset('img/default-profile.png');
        }
    }

    public function location() {
        return $this->belongsTo(Location::class, 'kd_location', 'kd_location');
    }

    public static function roleList()
    {
        return [
            'owner_or_manager_kantorpusat' => 'Owner/Manager Kantor Pusat',
            'manager_or_admin_toko' => 'Manager/Admin Toko',
            'production' => 'Production',
            'accounting' => 'Accounting',
            'sales' => 'Sales',
        ];
    }

    public function getHumanRoleAttribute()
    {
        return static::roleList()[$this->role];
    }

    public static function allowedRole()
    {
        return array_keys(static::roleList());
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new MailSendResetLink($token, $this->email));
    }

    public static function saveAttachment(UploadedFile $file, $title)
    {
        $fileName = str_slug($title).'-'.date("YmdHis").'.'.$file->getClientOriginalExtension();
        \Storage::disk('user')->putFileAs('', $file, $fileName);
        return $fileName;
    }

    public static function deleteAttachment($filename)
    {
        return \Storage::disk('user')->delete($filename);
    }
}

app/Http/Controllers/MasterData/CollectionController.php
<?php

namespace App\Http\Controllers\MasterData;

use App\Models\Collection;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CollectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collections = Collection::get();
        return view('toko.masterdata.collection.index', compact('collections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'collection' => 'required'
        ]);

        \DB::beginTransaction();
        try {
            $data = $request->only('collection');
            Collection::create($data);

            \DB::commit();

            \Session::flash('notification', ['level' => 'success', 'title' => 'Success', 'message' => 'Collection added successfully.']);
            return redirect()->route('collection.index');
        } catch (\Exception $e) {
            \DB::rollback();
            \Session::flash('notification', ['level' => 'error', 'title' => 'Error', 'message' => $e->getMessage()]);
            return back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $collection = Collection::where('id', $id)->firstOrFail();
        return view('toko.masterdata.collection.edit', compact('collection'))->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $collection = Collection::where('id', $id)->firstOrFail();
        $this->validate($request, [
            'collection' => 'required'
        ]);

        \DB::beginTransaction();
        try {
            $data = $request->only('collection');
            $collection->update($data);

            \DB::commit();

            \Session::flash('notification', ['level' => 'success', 'title' => 'Success', 'message' => 'Collection was updated.']);
            return redirect()->route('collection.index');
        } catch (\Exception $e) {
            \DB::rollback();
            \Session::flash('notification', ['level' => 'error', 'title' => 'Error', 'message' => $e->getMessage()]);
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $collection = Collection::where('id', $id)->firstOrFail();
        \DB::beginTransaction();
        try {
            $collection->delete();

            \DB::commit();

            \Session::flash('notification', ['level' => 'success', 'title' => 'Success', 'message' => 'Collection was deleted successfully.']);
            return redirect()->route('collection.index');
        } catch (\Exception $e) {
            \DB::rollback();
            \Session::flash('notification', ['level' => 'error', 'title' => 'Error', 'message' => $e->getMessage()]);
            return back()->withInput();
        }
    }
}

resources/views/toko/masterdata/datauser/edit.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Edit User</h4>
</div>
{!! Form::model($user, ['route' => ['data-user.update', $user->id], 'method' => 'patch', 'novalidate', 'class' => 'validate-form'])!!}
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="form-body">
                <div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
                    {!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
                    {{ Form::text('name', null, ['class' => 'form-control','required']) }}
                    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {!! $errors->has('username') ? 'has-error' : '' !!}">
                    {!! Form::label('username', 'Username') !!}
                    {{ Form::text('username', null, ['class' => 'form-control','required']) }}
                    {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
                    {!! Form::label('email', 'Email') !!}
                    {{ Form::email('email', null, ['class' => 'form-control','required']) }}
                    {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {!! $errors->has('password') ? 'has-error' : '' !!}">
                    {!! Form::label('password', 'Password') !!}
                    {{ Form::password('password', ['class' => 'form-control']) }}
                    {!! $errors->first('password', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {!! $errors->has('password_confirmation') ? 'has-error' : '' !!}">
                    {!! Form::label('password_confirmation', 'Confirm Password') !!}
                    {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                    {!! $errors->first('password_confirmation', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {!! $errors->has('role') ? 'has-error' : '' !!}">
                    {!! Form::label('role', 'Role') !!}
                    {{ Form::select('role', ['' => '']+App\Models\User::roleList(), null, ['class' => 'form-control select2','required', 'style' => 'width: 100%;', 'id' => 'roleU']) }}
                    {!! $errors->first('role', '<p class="help-block">:message</p>') !!}
                </div>
                <div id="locationFormU">
                    <div class="form-group {!! $errors->has('kd_location') ? 'has-error' : '' !!}">
                        {!! Form::label('kd_location', 'Location') !!}
                        {{ Form::select('kd_location', ['' => '']+App\Models\Location::pluck('location_name', 'kd_location')->all(), null, ['class' => 'form-control select2','required', 'style' => 'width: 100%;']) }}
                        {!! $errors->first('kd_location', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-default">Close</button>
    {!! Form::button('Simpan', ['type'=> 'submit', 'class'=>'btn btn-success']) !!}
</div>
{!! Form::close() !!}

<script>
    $(".validate-form").validate({
        highlight: function(element) {
            $(element).closest('.form-group').addClass('has-error');
        },
        unhighlight: function(element) {
            $(element).closest('.form-group').removeClass('has-error');
        },
        errorElement: 'span',
        errorClass: 'help-block',
        errorPlacement: function(error, element) {
            if (element.parents('div').hasClass('checkbox') || element.parents('div').hasClass('radio')) {
                error.appendTo(element.parent().parent().parent());
            } else if (element.parents('label').hasClass('checkbox-inline') || element.parents('label').hasClass('radio-inline')) {
                error.appendTo(element.parent().parent());
            } else if (element.parent('.input-group').length) {
                error.insertAfter(element.parent());
            } else if (element.parent().hasClass('uploader') || element.parents().hasClass('input-group')) {
                error.appendTo(element.parent().parent());
            } else {
                error.insertAfter(element);
            }
        }
    });
</script>

resources/views/toko/masterdata/datauser/index.blade.php
@extends('layouts.master-toko')

@section('custom-css')
    <link rel="stylesheet" href="{{ asset('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <link href="{{ asset('sweet-alert/sweetalert.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('plugin-js')
    <script src="{{ asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('sweet-alert/sweetalert.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/plugins/forms/validation/validate.min.js') }}"></script>
@endsection

@section('custom-script')
    <script type="text/javascript" src="{{ asset('js/sweetalert.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/jquery-form-validate.js') }}"></script>
    <script>
        $(function () {
            $('#tbUser').DataTable({
                responsive: true,
                columnDefs: [ {
                    targets: 4,
                    orderable: false
                } ]
            });
        })
    </script>
@endsection

@section('title')
    Data User - Saka Karya Bali
@endsection

@section('pageheader')
    <h1>
        Data User
        <small>Master Data</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}">Home</a></li>
        <li>Master Data</li>
        <li class="active">Data User</li>
    </ol>
@endsection

@section('content')
    <!-- /.col -->
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
            <a class="btn btn-block btn-social btn-google" data-toggle="modal" data-target="#addUser">
                <i class="fa fa-plus"></i> Add User
            </a>
            <br>
        </div>
    </div>
    <!-- /.col -->

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Data User</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tbUser" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Type</th>
                            <th class="text-center">Act</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->username }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    {{ $user->human_role }}
                                    <br>{{ $user->location ?  $user->location->location_name : '-' }}
                                </td>
                                <td class="text-center">
                                    {!! Form::model($user, ['route' => ['data-user.destroy', $user->id], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                                    <span data-toggle="tooltip" data-placement="top" title="Edit">
                                        <a href="{{ route('data-user.edit', $user->id)}}" data-target="#editUser" data-toggle="modal" class="btn btn-sm btn-info"><i class="fa fa-pencil"></i></a>
                                    </span>
                                    <span data-toggle="tooltip" data-placement="top" title="Delete User">
                                        <button type="button" class="btn btn-sm btn-danger js-submit-confirm"><i class="fa fa-trash"></i></button>
                                    </span>
                                    {!! Form::close()!!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

    <!-- MODALS -->
    <div class="modal fade" id="addUser">
        <div class="modal-dialog modal-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Add User</h4>
                </div>
                {!! Form::open(['route' => 'data-user.store', 'class' => 'jq-validate', 'method' => 'post', 'novalidate']) !!}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
                                {!! Form::label('name', 'Nama', ['class' => 'control-label']) !!}
                                {{ Form::text('name', null, ['class' => 'form-control','required']) }}
                                {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('username') ? 'has-error' : '' !!}">
                                {!! Form::label('username', 'Username') !!}
                                {{ Form::text('username', null, ['class' => 'form-control','required']) }}
                                {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
                                {!! Form::label('email', 'Email') !!}
                                {{ Form::email('email', null, ['class' => 'form-control','required']) }}
                                {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('password') ? 'has-error' : '' !!}">
                                {!! Form::label('password', 'Password') !!}
                                {{ Form::password('password', ['class' => 'form-control','required']) }}
                                {!! $errors->first('password', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('password_confirmation') ? 'has-error' : '' !!}">
                                {!! Form::label('password_confirmation', 'Confirm Password') !!}
                                {{ Form::password('password_confirmation', ['class' => 'form-control','required']) }}
                                {!! $errors->first('password_confirmation', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('role') ? 'has-error' : '' !!}">
                                {!! Form::label('role', 'Role') !!}
                                {{ Form::select('role', ['' => '']+App\Models\User::roleList(), null, ['class' => 'form-control select2','required', 'style' => 'width: 100%;', 'id' => 'role']) }}
                                {!! $errors->first('role', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div id="locationForm">
                                <div class="form-group {!! $errors->has('kd_location') ? 'has-error' : '' !!}">
                                    {!! Form::label('kd_location', 'Location') !!}
                                    {{ Form::select('kd_location', ['' => '']+App\Models\Location::pluck('location_name', 'kd_location')->all(), null, ['class' => 'form-control select2','required', 'style' => 'width: 100%;']) }}
                                    {!! $errors->first('kd_location', '<p class="help-block">:message</p>') !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-default">Close</button>
                    {!! Form::button('Simpan', ['type'=> 'submit', 'class'=>'btn btn-success']) !!}
                </div>
                {!! Form::close() !!}
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

    <div id="editUser" class="modal fade" tabindex="-1" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-center">
            <div class="modal-content">
                <div class="modal-body">
                    <img src="{{ asset('img/loading-spinner-grey.gif') }}" class="loading">
                    <span> &nbsp;&nbsp;Loading... </span>
                </div>
            </div>
        </div>
    </div>
@endsection